spring:
  datasource:
    url: YOUR_URL
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000
